// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_unsplash_demo/test/services/unsplash_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_unsplash_demo/models/photo.dart' as _i4;
import 'package:flutter_unsplash_demo/services/unsplash_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UnsplashService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnsplashService extends _i1.Mock implements _i2.UnsplashService {
  @override
  set onPhotosUpdated(_i2.PhotoUpdateCallback? _onPhotosUpdated) =>
      super.noSuchMethod(
        Invocation.setter(
          #onPhotosUpdated,
          _onPhotosUpdated,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<List<_i4.Photo>> getPhotos({
    int? page = 1,
    int? perPage = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPhotos,
          [],
          {
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue: _i3.Future<List<_i4.Photo>>.value(<_i4.Photo>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Photo>>.value(<_i4.Photo>[]),
      ) as _i3.Future<List<_i4.Photo>>);

  @override
  _i3.Future<List<_i4.Photo>> searchPhotos(
    String? query, {
    int? page = 1,
    int? perPage = 40,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPhotos,
          [query],
          {
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue: _i3.Future<List<_i4.Photo>>.value(<_i4.Photo>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Photo>>.value(<_i4.Photo>[]),
      ) as _i3.Future<List<_i4.Photo>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
